### ISSUE TITLE
Tracking issue for tests

### ISSUE THREAD

**Issue by Erik1000** [minkan-chat/server#15]
I have currently no time to add *good* tests. Especially the tests involving crypto need special attention and time.

We would need tests for:

- [ ] user id and user attribute removal
- [ ] key validation (if there are really keys for all operations)
- [ ] ``PrivateCertificate`` if it really fails if there are no encrypted secrets
- [ ] ``PublicCertificate`` really strips secret key material
- [ ] key policy (if really only curve 25519 suite is accepted and if unencrypted secret key material is rejected)
- [ ] challenge signature checks
- [ ] that refresh tokens are really denied after a use (this is probably pain to test, because it needs database I/O)
- [ ] that the check constraint in the database really rejects invalid names (pain to check too because of database I/O)
